project:
  type: website
  output-dir: docs
website:
  title: "OneSpark"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  search: true

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: journal
      dark: darkly
    css: styles.css
    toc: true
    include-after-body: footer.html
    



